version: '3.9'
   
services:

  web:
    build: .
    container_name: web
    restart: always
    command: flask run --host 0.0.0.0
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./sql/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local